version: "3.9"

services:
  devopsdb:
    image: meghanatharugu/docker-project:db-image
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
  

  application:
    image: meghanatharugu/docker-project:app-image
    ports:
      - "1234:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    
